server:
  port: 8080
  error:
    include-stacktrace: never
# logging:
#   level:
#     org.springframework.web: DEBUG
spring:
  profiles:
    active: @spring.profiles.active@
  output:
    ansi:
      enabled: always
--- 
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_URL}
    driver-class-name: ${PROD_DRIVER}
    username: ${PROD_USERNAME}
    password: ${PROD_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: dev
    import: file:./spring.env[.properties]
  datasource:
    url: ${DEV_URL}
    driver-class-name: ${DEV_DRIVER}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}